= Observability Workshop

== Agenda

* Intro
** WHOAMI
** How this Workshop is setup
** What is Observability
* Lab01 - Logging
** Consolidated Logging -- All services show up in elk
** Dynamic Logging Levels -- Only show debug on some
** Formatting
** Correlation IDs
* Lab01 Wrap Up
** When to use each, what are some pitfalls / best practices
* Lab02 - Tracing
** Zipkin Support For Services
** DataStore Tracing
** Debug slow transactions
* Lab03 - Metrics
* Lab04 - Observability Bugs


== Abstract
This workshop will be a hands on exploration of observability. There will be a microservice architecture system that we work to debug and add needed insights to. We will have a mix of services written in Ratpack, Micronaut, and Grails all interacting over a mix of methodologies; the setup will model an evolving system maintained by a number of teams. Work with logging techniques such as dynamic log levels, correlation IDs and formatting tricks. We will add distributed tracing to services, then actually debug issues. Metrics will also be covered. I’ll even introduce a few scenarios of observability gone wrong. Most of this workshop will be hands on the keyboard.
